---
title: "See Data, Speak Data Part 1: But I've go so much to say!"
author: "Len Kiefer"
date: "2016-12-17"
slug: "see-data-speak-data-part1"
tags: ["presentation"]
categories: ["presentation"]
summary: "See data speak data data visualziation and presentation thoughts"
---

IF YOU HAVE BEEN FOLLOWING along-welcome if you're stopping by for the first time-you'll have seen many different data visualizations that I have shared with you.  But let's take a step back and consider what to do with them.  I've got several thoughts on this topic that I will collect in a series I'll call "See Data, Speak Data".

## See Data, Speak Data

"See Data, Speak Data" was the title I gave to a keynote I recently gave to some analysts about how I use data in my professional life.  They'd asked me to come in and share how I use data and analytical tools to help me succeed at my work. My goal in this talk was not to just to cover the how, but also the why and perhaps most importantly the when of data visualization.  I structured my talk around two skills critical for successfully using data.  First, truly understanding the data, seeing data. And secondly, effectively communicating what you see, speaking data.

With access to so much data I've found that often times the impulse is to jump right into analysis.  Grab a bunch of data and start crunching numbers. Churn out some charts and tables.

And I totally get this impulse.  I have to constantly-and often unsuccessfully-fight this impulse. It's just so easy to get a whole bunch of data very quickly. And with the amazing tools that are proliferating and rapidly improving, it's increasingly easy to do amazing things with the data.  My days are filled with requests for analysis and when I start to hear a question the gears start turning in my head.  Even before the question is fully out I can hear my mind buzzing through all the tricks I've learned and I can feel excitement welling up about how this or that fancy chart would be perfect.
But it's usually not.

Often the answers are relatively simple, or if they are complex that very complexity calls for a simple, clear exposition.

I'm fortunate to know some extraordinarily smart people.  I'm talking world class experts that absolutely crush it in their area of expertise.  They've got so much to tell you, and if you can listen you can learn so much.  Problem is, these experts are usually talking to each other, and guess what?  The other experts they are talking to have so much to say too.

Look, you're smart and have a lot of great things to say. But part of the art of being an effective communicator is knowing when to speak.  And I think this is incredibly important for data analytics.  It's been something of a journey, but I have been trying to learn to see more, speak less when it comes to data. Seeing data means listening.

## Seeing data is listening

If you do start to listen and start to see more you might be surprised.  I was.

In my view communication is a critical skill for long-term success.  Writing well, speaking well can get you pretty far.  Those skills are often lacking, but one skill that's really rare to find is good listening skills.  Part of it's a function of our world these days.  Distractions are everywhere, technology encourages us to consume bite-sized morsels and move along. Click to the next thing.  The constant reinforcement of moving on to the next tweet, the next link trains us to have short attention spans.

Listening, like speaking or writing, is a skill.  We can develop it, but it takes practice and a conscious deliberate effort.  Good listeners have many different characteristics, but let's focus on the following traits of good listeners:

* They are present
* They are empathetic
* They pose questions

### Being present with your data

It's hard to be faithful to your data, even if you don't have a wandering eye.  You go through all the hard work of wrangling your data into an acceptable format.  You clean it, deal with outliers, and prepare it for analysis.  Just at that moment, when your data is ready for you, is the moment when you start to see your data as it truly is.

Almost always it's not perfect.  You don't have every column in your data.frame() you could have.  It wouldn't be that hard to add some additional observations.  Maybe the data is too aggregated and you could drill down.  Or maybe you need to roll observations up into some aggregate form.  When you've got your data in a useable form is when you can most easily see what it's not.

Maybe you are right. Maybe you do need to augment, aggregate or add to your data. But at some point you've got to deal with what you have and at that point you need to be present with it. 

### Being empathetic about your data

It may sound particularly odd to say you need to be empathetic about your data, but realize that it's ultimately about people. We're not yet (I think) reporting to cool calculating robot overlords, and so at some point both at the generation end of your data and at the receiving end of your analysis there are people involved. 

A startling lack of empathy pervades much data analysis, my own included.  If you're analyzing your data in a spreadsheet or computer program it's very easy to forget about those humans that helped generate your data and ultimately will consume your analysis. It's hard to overdo better understanding where (and why) your data came from and what your intended audience needs. 

### Posing questions about your data

Being present with and empathetic about your data will help you to ask better questions.  Good listeners aren't passive. They are not merely quiet, waiting for their turn to speak.  Good listeners ask questions and try to better understand not only what the speaker is saying, but what they are trying to say.

In terms of data, why were these data collected. What is the analyst hoping to accomplish with their analysis?  What might a consumer of that analysis be hoping to get out of it?  Asking good questions is an iterative process.  

## Speaking data often requires silence

If you can develop your data listening skills, your ability to truly see data, I think you'll find your data speaking skills dramatically improved.  But here's the thing.  As you expand your ability to see data, your ability to be present, to empathize and to ask good questions, you might find you have dramatically less to say.

That's no surprise.  Unfortunately, though you no doubt are smart and an expert in your own domain, so much of what you thought you had to say just isn't relevant. At least not now.

When I give talks, one of my challenges is that I often speak too fast.  I've had the benefit of speaker training and part of that is usually some form of video or audio recording. Looking at yourself on tape can be painful, but it really helps you to improve.  I tend to speak so fast because I'm usually excited to have the chance to talk before people, and because I feel like I've got so much to say.

But because most people cannot consume that much information in a single serving much of it would be lost.  It's often much better to slow down, say less and by doing so have more heard.

The same is true for data presentation, for speaking data.  

From the comfort of our own office and our own screen, we might like the noise.  Having all sorts of data we can quickly page through, filter, or interact with is often a pure joy for data geeks like me.  But it can often be bewildering or counter-productive to give so much to our audience.  In many context, less really is more.  

For data presentation: "perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away."

## What to take away?

How to know what to take away?  That's what this series of posts will be about.  In subsequent posts I'll share some examples of the thinking behind some successful, and unsuccessful, data visualizations and data presentations I've made.  In doing so I'll share with you how I approach seeing data, and how I approach speaking data. Should be fun.
