---
title: "Description and presentation, exploration and analysis"
author: "Len Kiefer"
date: "2017-02-07"
summary: "R statistics dataviz plotly housing mortgage data"
category: "presentation"
tags: ["presentation"]
slug: "describe-present"
---

THERE IS A LOVELY BOOK on writing style called *"Clear and Simple as the Truth"* by Francis-Noël Thomas and Mark Turner ([webpage]( http://classicprose.com/)). In it Thomas and Turner distinguish between several writing styles including practical style and classic style.  Practical style’s mode is description, while classic style’s is presentation ([see description]( http://classicprose.com/csguide.html#DESCRIPTION)).  

It strikes me that a similar distinction could be made when exploring statistics. Often, when we are exploring data we are in description mode.  Examining summary statistics, engaging in exploratory data analysis, these are descriptive activities.  If we hope for our analysis to impact the world or persuade someone at some point we need to move beyond exploration and into explanation, or even better presentation. How might that work for a project?

Most of what I've shared here is more for exploration than for explanation. But I have some ideas that we could explore, or rather I could *explain*, that would show the presentation side of data analysis. As we go forward this year I'm looking forward to sharing more thoughts on the explanation side of things.
