---
layout: post
title: "Housing Market Update: August 2016"
author: "Len Kiefer"
date: "August 26, 2016"
summary: "rstats data visualizations, mortgage data, maps"
group: navigation
theme :
  name : lentheme
---
<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>


```{r setup, include=FALSE}
opts_chunk$set(root.dir = "C:/Users/Leonard/Documents/webpage/live/lenkiefer.github.com/_Rmd")
```

IN THIS POST WE'LL REVIEW some recent housing market data.

```{r ,fig-setup-1, warning=FALSE, eval=T,cache=TRUE,echo=F, message=FALSE,fig.height=7,fig.width=7 }
#load some libraries
library(data.table)
library(reshape2)
library(stringr)
library(ggplot2)
library(scales)
library(ggthemes)
library(rgeos)
library(maptools)
library(albersusa)
library(dplyr)
library(tidyr)
library(ggalt)
library(viridis)
library(zoo)
library(readxl)
library(htmlTable)
mdata<-read_excel("data/chartbook aug 2016.xlsx",sheet="mrate")
mdata$date<-as.Date(mdata$date, format="%m/%d/%Y")
mdata<-data.table(mdata)
```


```{r ,fig-chartbk-1, warning=FALSE,eval=T,cache=TRUE,echo=F, message=FALSE,fig.height=4,fig.width=4 }
print.table<-data.table(mdata)[date>as.Date("2016-06-22"),
                               list(date=as.character(date,format="%B %d, %Y"),
                                    rate=format(rate, nsmall = 2))]

rownames(print.table)<-print.table$date
print.table$date<-NULL
htmlTable(print.table, header=c("30-year FRM"),
          row.names=print.table$date,row.label="Date",
          col.rgroup = c("none", "#F7F7F7"),caption="30-year fixed mortgage rates since Brexit",
          tfoot="Source: Freddie Mac Primary Mortgage Market Survey")
```

```{r ,fig-chartbk-2, warning=FALSE,eval=T,cache=TRUE,echo=F, message=FALSE,fig.height=4,fig.width=6 }
i<-34
    ggplot(data=mdata[year(date)==2016, ], aes(x=date,y=rate,label=rate))+geom_line()+theme_minimal()+
    theme(legend.position="none")+
    scale_x_date(date_breaks="1 month", date_labels="%b-%Y")+
    scale_y_continuous(limits=c(3,4),breaks=seq(3,4,.1))+
    geom_text(data=mdata[date>='2015-12-31' & week==i],nudge_x=10)+
    geom_point(data=mdata[date>='2015-12-31' & week==i],size=2,color="red",alpha=0.75)+
    labs(x="", y="Mortgage Rate (%)",
         title="30-year Fixed Mortgage Rate (%)",
         subtitle="weekly rates in 2016",
         caption="@lenkiefer Source: Freddie Mac Primary Mortgage Market Survey")+
    theme(plot.title=element_text(size=18))+
    theme(plot.caption=element_text(hjust=0,vjust=1,margin=margin(t=10)))+
    theme(plot.margin=unit(c(0.25,0.25,0.25,0.25),"cm"))+
    coord_cartesian(xlim=c(as.Date("2015-12-31"),as.Date("2016-8-31")), y=c(3.3,4))

```


