---
layout: post
title: "Housing's best year in a decade, remix"
author: "Len Kiefer"
date: "2017-01-14"
summary: "R statistics dataviz flexdashboard plotly"
group: navigation
theme :
  name : lentheme
---

IN THIS POST I PRESENT a remixed version of my [2016 year in review article]({{ site.url}}/chartbooks/dec2016/index.html).

By many measures 2016 was the best year for housing in a decade. Back in [May I shared]({{ site.url}}/chartbooks/may2016/index.html) some trends on housing markets and then in [December I did a full year recap]({{ site.url}}/chartbooks/dec2016/index.html).  This document is a flexdashboard version of my [December 2016 year-in-review article](http://lenkiefer.com/chartbooks/dec2016/index.html).

I'm looking to make use of flexdashboards and try some more things. In particular I'm looking to add more htmlwidgets and try some more advanced formatting options.  But putting this version together helped me learn a few tricks.

All the source code is available in the tab at the right.  

You can see a fullscreen version [here]({{ site.url}}/chartbooks/jan2017/review2016sidebar.html). 

<iframe src="{{ site.url}}/chartbooks/jan2017/review2016sidebar.html" height="800" width="1200"></iframe>