---
layout: post
title: "Flexin' Friday"
author: "Len Kiefer"
date: "2017-01-20"
summary: "R statistics dataviz remix flexdashboard"
group: navigation
theme :
  name : lentheme
---

WE WORKED OUT A [VISUALIZATION REMIX ON WEDNESDAY](http://lenkiefer.com/2017/01/18/workin-workout) and now that it's Friday time to flex a little.  In this post I'm going to remix the remix into a [flexdashboard](http://rmarkdown.rstudio.com/flexdashboard/index.html).

I made this dashboard using [crosstalk]( http://rstudio.github.io/crosstalk/) and [plotly]( https://plot.ly/r/). By using [htmlwidgets]( http://www.htmlwidgets.org/) we can create an interactive dashboard in a static webpage.

In this version I added an animation.  In order to get [the animation to work](https://cpsievert.github.io/plotly_book/key-frame-animations.html) you'll need the [development version of plotly](https://github.com/ropensci/plotly) for R.

It took me a while to get the animation to work, but basically I combined a [ggplot2](http://ggplot2.org/) graph with plotly using [ggplotly](https://plot.ly/ggplot2/).  ggplotly doesn't support all features of ggplot2, for example rug plots are out, but it does quite a lot.  I'm fond of thinking if you can make a scatterplot along with line segments and polygons, you basically can create any visualization you want (*you might also need curves if you believe in them*).

Check out the [fullscreen version here.]({{ site.url}}/chartbooks/jan2017/friday_flexin.html)

Source code is available on the upper right corner.

<iframe src="{{ site.url}}/chartbooks/jan2017/friday_flexin.html" height="850" width="1200"></iframe>